# Generated by Django 4.2.2 on 2024-07-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nickName',
            field=models.TextField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profilePhoto',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
