# Generated by Django 4.2.2 on 2023-12-04 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nick_name',
            field=models.TextField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
