# Generated by Django 4.2.2 on 2024-07-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='place',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
