# Generated by Django 4.2.2 on 2024-02-05 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_customuser_nick_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='place',
            field=models.TextField(default='kozhikode', max_length=200),
        ),
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=50)),
                ('crop_stage', models.TextField(max_length=50)),
                ('crop_area', models.TextField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.customuser')),
            ],
        ),
    ]
