# Generated by Django 4.2.2 on 2024-07-11 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
