# Generated by Django 4.2.2 on 2024-02-05 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_customuser_place_crops'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crops',
            new_name='Crop',
        ),
    ]
