# Generated by Django 5.0.2 on 2024-02-08 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_rename_crops_crop'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField(max_length=25)),
                ('description', models.TextField(max_length=100)),
                ('time', models.DateTimeField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.crop')),
            ],
        ),
        migrations.CreateModel(
            name='CropSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.FloatField()),
                ('nitrogen', models.SmallIntegerField()),
                ('phosphorous', models.SmallIntegerField()),
                ('potassium', models.SmallIntegerField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.crop')),
            ],
        ),
    ]
