# Generated by Django 4.2.2 on 2024-07-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.TextField(blank=True, max_length=60, null=True),
        ),
    ]
