# Generated by Django 5.0.2 on 2024-02-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0005_cropschedule_cropsensordata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropschedule',
            name='activity',
            field=models.CharField(max_length=25),
        ),
    ]
