# Generated by Django 4.2.2 on 2024-07-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0005_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='nickName',
            new_name='name',
        ),
    ]
