# Generated by Django 5.0.2 on 2024-02-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_alter_cropschedule_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='crop_area',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='crop_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='crop_stage',
            new_name='stage',
        ),
        migrations.AddField(
            model_name='crop',
            name='grown',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cropsensordata',
            name='phStatus',
            field=models.CharField(default='optimal', max_length=20),
        ),
    ]
