# Generated by Django 5.0.2 on 2024-02-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0008_rename_crop_area_crop_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropsensordata',
            name='condition',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
