# Generated by Django 5.0.2 on 2024-02-08 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0009_cropsensordata_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='nick_name',
            new_name='nickName',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_photo',
            new_name='profilePhoto',
        ),
    ]
